packages:
  - app
  - ui
  - wasm
  - log
  - store

onlyBuiltDependencies:
  - '@applemusic-like-lyrics/lyric'
  - '@parcel/watcher'
  - electron
  - electron-winstaller
  - esbuild

registry: https://registry.npmmirror.com
