// This file is auto-generated by scripts/env.ts

interface ENV {
  readonly APP_MODE: string;
  readonly APP_DEBUG_PORT: number;
  readonly NCM_SERVER_PORT: number;
  readonly GO_SERVER_PORT: number;
  readonly EXPRESS_SERVER_PORT: number;
  readonly VITE_SERVER_PORT: number;
  readonly UI_LOG_LEVEL: string;
  readonly APP_LOG_LEVEL: string;
  readonly APP_NAME: string;
  readonly APP_DESC: string;
  readonly APP_SCHEME: string;
  readonly APP_PROTOCOL: string;
  readonly APP_SCHEME_FILE_HOSTNAME: string;
}

declare namespace NodeJS {
  interface ProcessEnv extends ENV {}
}
