// This file is auto-generated by scripts/env.ts

interface ENV {
  readonly NCM_SERVER_PORT: number;
  readonly GO_SERVER_PORT: number;
  readonly GO_SERVER_STORE_PATH: string;
  readonly EXPRESS_SERVER_PORT: number;
  readonly VITE_SERVER_PORT: number;
  readonly UI_LOG_LEVEL: string;
  readonly APP_LOG_LEVEL: string;
  readonly APP_NAME: string;
  readonly APP_SCHEME: string;
  readonly APP_PROTOCOL: string;
}

type EnvLogLevel = "TRACE" | "DEBUG" | "INFO" | "WARN" | "ERROR" | "NONE";
