// This file is auto-generated by scripts/generate-ncm-mod-def.ts.
import { createRequire } from "node:module";
import type { ModuleDefinition } from "@neteasecloudmusicapienhanced/api/server.js";

const require = createRequire(import.meta.url);

const moduleDefs: ModuleDefinition[] = [
  {
    identifier: "album",
    route: "/album",
    module: require("@neteasecloudmusicapienhanced/api/module/album")
  },
  {
    identifier: "album_detail_dynamic",
    route: "/album/detail/dynamic",
    module: require("@neteasecloudmusicapienhanced/api/module/album_detail_dynamic")
  },
  {
    identifier: "album_new",
    route: "/album/new",
    module: require("@neteasecloudmusicapienhanced/api/module/album_new")
  },
  {
    identifier: "album_sub",
    route: "/album/sub",
    module: require("@neteasecloudmusicapienhanced/api/module/album_sub")
  },
  {
    identifier: "album_sublist",
    route: "/album/sublist",
    module: require("@neteasecloudmusicapienhanced/api/module/album_sublist")
  },
  {
    identifier: "artist_album",
    route: "/artist/album",
    module: require("@neteasecloudmusicapienhanced/api/module/artist_album")
  },
  {
    identifier: "artist_desc",
    route: "/artist/desc",
    module: require("@neteasecloudmusicapienhanced/api/module/artist_desc")
  },
  {
    identifier: "artist_detail",
    route: "/artist/detail",
    module: require("@neteasecloudmusicapienhanced/api/module/artist_detail")
  },
  {
    identifier: "artist_follow_count",
    route: "/artist/follow/count",
    module: require("@neteasecloudmusicapienhanced/api/module/artist_follow_count")
  },
  {
    identifier: "artist_sub",
    route: "/artist/sub",
    module: require("@neteasecloudmusicapienhanced/api/module/artist_sub")
  },
  {
    identifier: "artist_sublist",
    route: "/artist/sublist",
    module: require("@neteasecloudmusicapienhanced/api/module/artist_sublist")
  },
  {
    identifier: "artist_top_song",
    route: "/artist/top/song",
    module: require("@neteasecloudmusicapienhanced/api/module/artist_top_song")
  },
  {
    identifier: "banner",
    route: "/banner",
    module: require("@neteasecloudmusicapienhanced/api/module/banner")
  },
  {
    identifier: "captcha_sent",
    route: "/captcha/sent",
    module: require("@neteasecloudmusicapienhanced/api/module/captcha_sent")
  },
  {
    identifier: "cloudsearch",
    route: "/cloudsearch",
    module: require("@neteasecloudmusicapienhanced/api/module/cloudsearch")
  },
  {
    identifier: "comment",
    route: "/comment",
    module: require("@neteasecloudmusicapienhanced/api/module/comment")
  },
  {
    identifier: "comment_like",
    route: "/comment/like",
    module: require("@neteasecloudmusicapienhanced/api/module/comment_like")
  },
  {
    identifier: "comment_new",
    route: "/comment/new",
    module: require("@neteasecloudmusicapienhanced/api/module/comment_new")
  },
  {
    identifier: "daily_signin",
    route: "/daily_signin",
    module: require("@neteasecloudmusicapienhanced/api/module/daily_signin")
  },
  {
    identifier: "fm_trash",
    route: "/fm/trash",
    module: require("@neteasecloudmusicapienhanced/api/module/fm_trash")
  },
  {
    identifier: "hug_comment",
    route: "/hug/comment",
    module: require("@neteasecloudmusicapienhanced/api/module/hug_comment")
  },
  {
    identifier: "like",
    route: "/like",
    module: require("@neteasecloudmusicapienhanced/api/module/like")
  },
  {
    identifier: "likelist",
    route: "/likelist",
    module: require("@neteasecloudmusicapienhanced/api/module/likelist")
  },
  {
    identifier: "listen_data_realtime_report",
    route: "/listen/data/realtime/report",
    module: require("@neteasecloudmusicapienhanced/api/module/listen_data_realtime_report")
  },
  {
    identifier: "listen_data_report",
    route: "/listen/data/report",
    module: require("@neteasecloudmusicapienhanced/api/module/listen_data_report")
  },
  {
    identifier: "listen_data_today_song",
    route: "/listen/data/today/song",
    module: require("@neteasecloudmusicapienhanced/api/module/listen_data_today_song")
  },
  {
    identifier: "listen_data_total",
    route: "/listen/data/total",
    module: require("@neteasecloudmusicapienhanced/api/module/listen_data_total")
  },
  {
    identifier: "login",
    route: "/login",
    module: require("@neteasecloudmusicapienhanced/api/module/login")
  },
  {
    identifier: "login_cellphone",
    route: "/login/cellphone",
    module: require("@neteasecloudmusicapienhanced/api/module/login_cellphone")
  },
  {
    identifier: "login_qr_check",
    route: "/login/qr/check",
    module: require("@neteasecloudmusicapienhanced/api/module/login_qr_check")
  },
  {
    identifier: "login_qr_create",
    route: "/login/qr/create",
    module: require("@neteasecloudmusicapienhanced/api/module/login_qr_create")
  },
  {
    identifier: "login_qr_key",
    route: "/login/qr/key",
    module: require("@neteasecloudmusicapienhanced/api/module/login_qr_key")
  },
  {
    identifier: "login_refresh",
    route: "/login/refresh",
    module: require("@neteasecloudmusicapienhanced/api/module/login_refresh")
  },
  {
    identifier: "login_status",
    route: "/login/status",
    module: require("@neteasecloudmusicapienhanced/api/module/login_status")
  },
  {
    identifier: "logout",
    route: "/logout",
    module: require("@neteasecloudmusicapienhanced/api/module/logout")
  },
  {
    identifier: "lyric_new",
    route: "/lyric/new",
    module: require("@neteasecloudmusicapienhanced/api/module/lyric_new")
  },
  {
    identifier: "mv_detail",
    route: "/mv/detail",
    module: require("@neteasecloudmusicapienhanced/api/module/mv_detail")
  },
  {
    identifier: "mv_sub",
    route: "/mv/sub",
    module: require("@neteasecloudmusicapienhanced/api/module/mv_sub")
  },
  {
    identifier: "mv_sublist",
    route: "/mv/sublist",
    module: require("@neteasecloudmusicapienhanced/api/module/mv_sublist")
  },
  {
    identifier: "mv_url",
    route: "/mv/url",
    module: require("@neteasecloudmusicapienhanced/api/module/mv_url")
  },
  {
    identifier: "personal_fm",
    route: "/personal_fm",
    module: require("@neteasecloudmusicapienhanced/api/module/personal_fm")
  },
  {
    identifier: "personalized",
    route: "/personalized",
    module: require("@neteasecloudmusicapienhanced/api/module/personalized")
  },
  {
    identifier: "playlist_catlist",
    route: "/playlist/catlist",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_catlist")
  },
  {
    identifier: "playlist_cover_update",
    route: "/playlist/cover/update",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_cover_update")
  },
  {
    identifier: "playlist_create",
    route: "/playlist/create",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_create")
  },
  {
    identifier: "playlist_delete",
    route: "/playlist/delete",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_delete")
  },
  {
    identifier: "playlist_detail",
    route: "/playlist/detail",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_detail")
  },
  {
    identifier: "playlist_detail_rcmd_get",
    route: "/playlist/detail/rcmd/get",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_detail_rcmd_get")
  },
  {
    identifier: "playlist_highquality_tags",
    route: "/playlist/highquality/tags",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_highquality_tags")
  },
  {
    identifier: "playlist_hot",
    route: "/playlist/hot",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_hot")
  },
  {
    identifier: "playlist_privacy",
    route: "/playlist/privacy",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_privacy")
  },
  {
    identifier: "playlist_subscribe",
    route: "/playlist/subscribe",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_subscribe")
  },
  {
    identifier: "playlist_subscribers",
    route: "/playlist/subscribers",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_subscribers")
  },
  {
    identifier: "playlist_tracks",
    route: "/playlist/tracks",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_tracks")
  },
  {
    identifier: "playlist_update",
    route: "/playlist/update",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_update")
  },
  {
    identifier: "playlist_update_playcount",
    route: "/playlist/update/playcount",
    module: require("@neteasecloudmusicapienhanced/api/module/playlist_update_playcount")
  },
  {
    identifier: "playmode_intelligence_list",
    route: "/playmode/intelligence/list",
    module: require("@neteasecloudmusicapienhanced/api/module/playmode_intelligence_list")
  },
  {
    identifier: "recommend_resource",
    route: "/recommend/resource",
    module: require("@neteasecloudmusicapienhanced/api/module/recommend_resource")
  },
  {
    identifier: "recommend_songs",
    route: "/recommend/songs",
    module: require("@neteasecloudmusicapienhanced/api/module/recommend_songs")
  },
  {
    identifier: "recommend_songs_dislike",
    route: "/recommend/songs/dislike",
    module: require("@neteasecloudmusicapienhanced/api/module/recommend_songs_dislike")
  },
  {
    identifier: "relay_play_state_submit",
    route: "/relay/play/state/submit",
    module: require("@neteasecloudmusicapienhanced/api/module/relay_play_state_submit")
  },
  {
    identifier: "scrobble",
    route: "/scrobble",
    module: require("@neteasecloudmusicapienhanced/api/module/scrobble")
  },
  {
    identifier: "search",
    route: "/search",
    module: require("@neteasecloudmusicapienhanced/api/module/search")
  },
  {
    identifier: "search_default",
    route: "/search/default",
    module: require("@neteasecloudmusicapienhanced/api/module/search_default")
  },
  {
    identifier: "search_hot",
    route: "/search/hot",
    module: require("@neteasecloudmusicapienhanced/api/module/search_hot")
  },
  {
    identifier: "search_hot_detail",
    route: "/search/hot/detail",
    module: require("@neteasecloudmusicapienhanced/api/module/search_hot_detail")
  },
  {
    identifier: "search_multimatch",
    route: "/search/multimatch",
    module: require("@neteasecloudmusicapienhanced/api/module/search_multimatch")
  },
  {
    identifier: "search_suggest",
    route: "/search/suggest",
    module: require("@neteasecloudmusicapienhanced/api/module/search_suggest")
  },
  {
    identifier: "simi_artist",
    route: "/simi/artist",
    module: require("@neteasecloudmusicapienhanced/api/module/simi_artist")
  },
  {
    identifier: "simi_mv",
    route: "/simi/mv",
    module: require("@neteasecloudmusicapienhanced/api/module/simi_mv")
  },
  {
    identifier: "simi_playlist",
    route: "/simi/playlist",
    module: require("@neteasecloudmusicapienhanced/api/module/simi_playlist")
  },
  {
    identifier: "simi_song",
    route: "/simi/song",
    module: require("@neteasecloudmusicapienhanced/api/module/simi_song")
  },
  {
    identifier: "song_chorus",
    route: "/song/chorus",
    module: require("@neteasecloudmusicapienhanced/api/module/song_chorus")
  },
  {
    identifier: "song_detail",
    route: "/song/detail",
    module: require("@neteasecloudmusicapienhanced/api/module/song_detail")
  },
  {
    identifier: "song_dynamic_cover",
    route: "/song/dynamic/cover",
    module: require("@neteasecloudmusicapienhanced/api/module/song_dynamic_cover")
  },
  {
    identifier: "song_order_update",
    route: "/song/order/update",
    module: require("@neteasecloudmusicapienhanced/api/module/song_order_update")
  },
  {
    identifier: "song_red_count",
    route: "/song/red/count",
    module: require("@neteasecloudmusicapienhanced/api/module/song_red_count")
  },
  {
    identifier: "song_url",
    route: "/song/url",
    module: require("@neteasecloudmusicapienhanced/api/module/song_url")
  },
  {
    identifier: "song_url_v1",
    route: "/song/url/v1",
    module: require("@neteasecloudmusicapienhanced/api/module/song_url_v1")
  },
  {
    identifier: "song_wiki_summary",
    route: "/song/wiki/summary",
    module: require("@neteasecloudmusicapienhanced/api/module/song_wiki_summary")
  },
  {
    identifier: "top_playlist",
    route: "/top/playlist",
    module: require("@neteasecloudmusicapienhanced/api/module/top_playlist")
  },
  {
    identifier: "top_playlist_highquality",
    route: "/top/playlist/highquality",
    module: require("@neteasecloudmusicapienhanced/api/module/top_playlist_highquality")
  },
  {
    identifier: "top_song",
    route: "/top/song",
    module: require("@neteasecloudmusicapienhanced/api/module/top_song")
  },
  {
    identifier: "toplist",
    route: "/toplist",
    module: require("@neteasecloudmusicapienhanced/api/module/toplist")
  },
  {
    identifier: "toplist_artist",
    route: "/toplist/artist",
    module: require("@neteasecloudmusicapienhanced/api/module/toplist_artist")
  },
  {
    identifier: "ugc_album_get",
    route: "/ugc/album/get",
    module: require("@neteasecloudmusicapienhanced/api/module/ugc_album_get")
  },
  {
    identifier: "ugc_artist_get",
    route: "/ugc/artist/get",
    module: require("@neteasecloudmusicapienhanced/api/module/ugc_artist_get")
  },
  {
    identifier: "ugc_song_get",
    route: "/ugc/song/get",
    module: require("@neteasecloudmusicapienhanced/api/module/ugc_song_get")
  },
  {
    identifier: "user_account",
    route: "/user/account",
    module: require("@neteasecloudmusicapienhanced/api/module/user_account")
  },
  {
    identifier: "user_detail",
    route: "/user/detail",
    module: require("@neteasecloudmusicapienhanced/api/module/user_detail")
  },
  {
    identifier: "user_playlist",
    route: "/user/playlist",
    module: require("@neteasecloudmusicapienhanced/api/module/user_playlist")
  },
  {
    identifier: "user_record",
    route: "/user/record",
    module: require("@neteasecloudmusicapienhanced/api/module/user_record")
  }
];

export default moduleDefs;
