import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { readFileSync, writeFileSync } from "node:fs";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const envDir = join(__dirname, "../");
const typeFile = join(__dirname, "../types/env.d.ts");

type EnvName = string;

type EnvValue = string | number | boolean;

export type Env = Record<EnvName, EnvValue>;

export function loadEnv(mode?: string) {
  console.log(`Loading env for mode: ${mode || "default"}`);
  return getEnvNames(mode).reduce(
    (env, name) => {
      const parsedEnv = parseEnv(join(envDir, name));
      console.log(`  Loaded ${name}:`, JSON.stringify(parsedEnv, null, 2));
      return { ...env, ...parsedEnv };
    },
    <Env>{}
  );
}

export function generateEnvType(env: Env, file = typeFile) {
  const contentLines: string[] = [];
  for (const key in env) {
    contentLines.push(`readonly ${key}: ${typeof env[key]};`);
  }

  const content = `// This file is auto-generated by scripts/env.ts

interface ENV {
  ${contentLines.join("\n  ")}
}

declare namespace NodeJS {
  interface ProcessEnv extends ENV {}
}

type EnvLogLevel = "TRACE" | "DEBUG" | "INFO" | "WARN" | "ERROR" | "NONE";
`;

  writeFileSync(file, content, "utf-8");
}

function getEnvNames(mode?: string) {
  const names = [".env"];
  if (mode) {
    names.unshift(`.env.${mode}`);
  } else {
    const args = process.argv;
    const modeIndex = args.findIndex((arg) => arg === "--env" || arg === "-e");
    if (modeIndex !== -1 && modeIndex + 1 < args.length) {
      const mode = args[modeIndex + 1];
      names.unshift(`.env.${mode}`);
    }
  }
  return names;
}

function parseEnv(filePath: string) {
  try {
    return readFileSync(filePath, "utf-8")
      .split("\n") // 按行分割
      .filter(Boolean) // 过滤掉空行
      .map(handleLine) // 处理每一行，返回 { name, value } 或 null
      .filter(Boolean) // 过滤掉 null
      .reduce(
        // 将 { name, value } 转换为对象
        (env, result) => {
          env[result!.name] = result!.value;
          return env;
        },
        <Env>{}
      );
  } catch (err) {
    console.warn("parseEnv", err);
    return <Env>{};
  }
}

function handleLine(line: string) {
  if (line === "" || line.startsWith("#")) return null;

  const [name, ...rest] = line.split("=");
  const value = rest.join("=").trim();
  if (name && rest.length > 0) {
    return {
      name: handleName(name),
      value: handleValue(value)
    };
  }

  return null;
}

function handleName(name: string): EnvName {
  return name.trim();
}

function handleValue(value: string): EnvValue {
  value = value.trim();
  if (value === "true") return true;
  if (value === "false") return false;
  if (value === "") return "";
  const num = Number(value);
  if (!isNaN(num)) return num;
  return String(value);
}
