import { fileURLToPath } from "node:url";
import { join } from "node:path";
import { readFileSync, writeFileSync } from "node:fs";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const envDir = join(__dirname, "../");
const typeFile = join(__dirname, "../types/env.d.ts");

function loadEnv(mode?: string) {
  console.log(`Loading env for mode: ${mode || "default"}`);
  return getEnvNames(mode).reduce(
    (env, name) => {
      const parsedEnv = parseEnv(join(envDir, name));
      console.log(`  Loaded ${name}:`, JSON.stringify(parsedEnv, null, 2));
      return { ...env, ...parsedEnv };
    },
    <Record<string, string | number | boolean>>{}
  );
}

function getEnvNames(mode?: string) {
  const names = [".env"];
  if (mode) {
    names.unshift(`.env.${mode}`);
  } else {
    const args = process.argv;
    const modeIndex = args.findIndex((arg) => arg === "--env" || arg === "-e");
    if (modeIndex !== -1 && modeIndex + 1 < args.length) {
      const mode = args[modeIndex + 1];
      names.unshift(`.env.${mode}`);
    }
  }
  return names;
}

function parseEnv(filePath: string) {
  const env: Record<string, string | number | boolean> = {};
  try {
    const envStr = readFileSync(filePath, "utf-8");
    if (envStr) {
      const lines = envStr.split("\n");
      for (const line of lines) {
        if (line === "" || line.startsWith("#")) continue;
        const [key, ...rest] = line.split("=");
        if (key && rest.length > 0) {
          env[key.trim()] = parseValue(rest.join("=").trim());
        }
      }
    }
    return env;
  } catch {
    return env;
  }
}

function parseValue(value: string): string | number | boolean {
  if (value === "true") return true;
  if (value === "false") return false;
  if (value === "") return "";
  const num = Number(value);
  if (!isNaN(num)) return num;
  return value;
}

function generateEnvType(env: Record<string, string | number | boolean>, file = typeFile) {
  const contentLines: string[] = [];
  for (const key in env) {
    const value = env[key];
    let type: string;
    if (typeof value === "boolean") {
      type = "boolean";
    } else if (typeof value === "number") {
      type = "number";
    } else {
      type = "string";
    }
    contentLines.push(`readonly ${key}: ${type};`);
  }

  const content = `// This file is auto-generated by scripts/env.ts

interface ENV {
  ${contentLines.join("\n  ")}
}

type EnvLogLevel = "TRACE" | "DEBUG" | "INFO" | "WARN" | "ERROR" | "NONE";
`;

  writeFileSync(file, content, "utf-8");
}

export { loadEnv, generateEnvType };
