// This script is generated by codex
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const SCRIPT_DIR = fileURLToPath(new URL(".", import.meta.url));
export const REPO_ROOT = resolve(SCRIPT_DIR, "..");
export const UI_NETEASE_API_DIR = resolve(REPO_ROOT, "packages/ui/src/common/netease/api");
export const APP_NCM_MODULE_DEF_FILE = resolve(
  REPO_ROOT,
  "packages/app/src/services/ncm/ncmModDef.ts"
);
export const NCM_API_MODULE_DIR = resolve(
  REPO_ROOT,
  "node_modules/@neteasecloudmusicapienhanced/api/module"
);

const GENERATED_HEADER = "// This file is auto-generated by scripts/generate-ncm-mod-def.ts.\n";

const SPECIAL_ROUTE_MODULE_IDENTIFIERS = new Map<string, string>([
  ["/daily_signin", "daily_signin"]
]);

export type RouteSource = {
  filePath: string;
  line: number;
  column: number;
};

export type RouteDiagnostic = RouteSource & {
  message: string;
};

export type RouteCollectResult = {
  routes: Map<string, RouteSource[]>;
  unresolvedCalls: RouteDiagnostic[];
};

export type NcmModuleDefinitionEntry = {
  identifier: string;
  route: string;
  moduleFile: string;
};

export type NcmModuleDefinitionResult = {
  entries: NcmModuleDefinitionEntry[];
  missingModuleFiles: RouteDiagnostic[];
};

export function collectNeteaseApiRoutes(apiDir = UI_NETEASE_API_DIR): RouteCollectResult {
  const result = createCollectResult();
  for (const filePath of listTypescriptFiles(apiDir)) {
    if (filePath.endsWith("request.ts")) continue;
    mergeCollectResult(result, collectRoutesFromSourceFile(filePath));
  }
  return result;
}

export function collectRoutesFromSourceFile(filePath: string): RouteCollectResult {
  return collectRoutesFromSourceText(readFileSync(filePath, "utf-8"), filePath);
}

export function collectRoutesFromSourceText(
  sourceText: string,
  filePath: string
): RouteCollectResult {
  const sourceFile = ts.createSourceFile(filePath, sourceText, ts.ScriptTarget.Latest, true);
  const constantScopes: RouteConstantScope[] = [new Map()];
  const result = createCollectResult();

  function visit(node: ts.Node) {
    if (ts.isBlock(node)) {
      constantScopes.push(new Map());
      ts.forEachChild(node, visit);
      constantScopes.pop();
      return;
    }

    if (isStaticRouteConstantDeclaration(node)) {
      const routes = resolveRouteExpression(node.initializer, sourceFile, constantScopes);
      if (routes.length > 0) currentScope(constantScopes).set(node.name.text, routes);
    }

    if (ts.isCallExpression(node) && isApiRequestCall(node)) {
      const routes = resolveApiRequestRoutes(node, sourceFile, constantScopes);
      if (routes.length > 0) {
        const source = getSourceLocation(sourceFile, filePath, node);
        for (const route of routes) addRoute(result.routes, route, source);
      } else {
        result.unresolvedCalls.push({
          ...getSourceLocation(sourceFile, filePath, node),
          message: "Unable to resolve apiRequest route"
        });
      }
    }

    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return result;
}

export function createNcmModuleDefinitions(
  routes: Iterable<string>,
  moduleDir = NCM_API_MODULE_DIR
): NcmModuleDefinitionResult {
  const entries: NcmModuleDefinitionEntry[] = [];
  const missingModuleFiles: RouteDiagnostic[] = [];

  for (const route of [...new Set(routes)].sort()) {
    const identifier = routeToModuleIdentifier(route);
    const moduleFile = join(moduleDir, `${identifier}.js`);
    entries.push({ identifier, route, moduleFile });
    if (!existsSync(moduleFile)) {
      missingModuleFiles.push({
        filePath: moduleFile,
        line: 1,
        column: 1,
        message: `Missing upstream NCM module for route ${route}`
      });
    }
  }

  return { entries, missingModuleFiles };
}

export function routeToModuleIdentifier(route: string) {
  return (
    SPECIAL_ROUTE_MODULE_IDENTIFIERS.get(route) ?? route.replace(/^\//, "").replaceAll("/", "_")
  );
}

export function generateNcmModuleDefContent(apiDir = UI_NETEASE_API_DIR) {
  const collected = collectNeteaseApiRoutes(apiDir);
  if (collected.unresolvedCalls.length > 0) {
    throw new Error(formatDiagnostics(collected.unresolvedCalls));
  }

  const definitions = createNcmModuleDefinitions(collected.routes.keys());
  if (definitions.missingModuleFiles.length > 0) {
    throw new Error(formatDiagnostics(definitions.missingModuleFiles));
  }

  return renderNcmModuleDef(definitions.entries);
}

export function renderNcmModuleDef(entries: NcmModuleDefinitionEntry[]) {
  const body = entries
    .map(
      (entry) => `  {
    identifier: "${entry.identifier}",
    route: "${entry.route}",
    module: require("@neteasecloudmusicapienhanced/api/module/${entry.identifier}")
  }`
    )
    .join(",\n");

  return `${GENERATED_HEADER}import { createRequire } from "node:module";
import type { ModuleDefinition } from "@neteasecloudmusicapienhanced/api/server.js";

const require = createRequire(import.meta.url);

const moduleDefs: ModuleDefinition[] = [
${body}
];

export default moduleDefs;
`;
}

export function formatDiagnostics(diagnostics: RouteDiagnostic[]) {
  return diagnostics
    .map((diagnostic) => {
      const filePath = relative(REPO_ROOT, diagnostic.filePath);
      return `${filePath}:${diagnostic.line}:${diagnostic.column} ${diagnostic.message}`;
    })
    .join("\n");
}

function listTypescriptFiles(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const filePath = join(dir, entry.name);
    if (entry.isDirectory()) return listTypescriptFiles(filePath);
    if (entry.isFile() && filePath.endsWith(".ts") && !filePath.endsWith(".d.ts"))
      return [filePath];
    return [];
  });
}

type RouteConstantScope = Map<string, string[]>;

function resolveApiRequestRoutes(
  node: ts.CallExpression,
  sourceFile: ts.SourceFile,
  constantScopes: RouteConstantScope[]
) {
  const firstArg = node.arguments[0];
  if (!firstArg) return [];

  if (ts.isObjectLiteralExpression(firstArg)) {
    return firstArg.properties.flatMap((property) => {
      if (!ts.isPropertyAssignment(property) || !isUrlPropertyName(property.name)) return [];
      return resolveRouteExpression(property.initializer, sourceFile, constantScopes);
    });
  }

  return resolveRouteExpression(firstArg, sourceFile, constantScopes);
}

function resolveRouteExpression(
  expression: ts.Expression,
  sourceFile: ts.SourceFile,
  constantScopes: RouteConstantScope[]
): string[] {
  if (ts.isStringLiteralLike(expression)) {
    return routeFromString(expression.text);
  }

  if (ts.isTemplateExpression(expression)) {
    return routeFromTemplateExpression(expression);
  }

  if (ts.isIdentifier(expression)) {
    return resolveConstantRoutes(expression.text, constantScopes);
  }

  if (ts.isConditionalExpression(expression)) {
    return uniqueRoutes([
      ...resolveRouteExpression(expression.whenTrue, sourceFile, constantScopes),
      ...resolveRouteExpression(expression.whenFalse, sourceFile, constantScopes)
    ]);
  }

  if (ts.isParenthesizedExpression(expression)) {
    return resolveRouteExpression(expression.expression, sourceFile, constantScopes);
  }

  if (ts.isAsExpression(expression) || ts.isTypeAssertionExpression(expression)) {
    return resolveRouteExpression(expression.expression, sourceFile, constantScopes);
  }

  if (ts.isSatisfiesExpression(expression)) {
    return resolveRouteExpression(expression.expression, sourceFile, constantScopes);
  }

  if (ts.isNonNullExpression(expression)) {
    return resolveRouteExpression(expression.expression, sourceFile, constantScopes);
  }

  if (
    ts.isBinaryExpression(expression) &&
    expression.operatorToken.kind === ts.SyntaxKind.PlusToken
  ) {
    const left = resolveRawStringExpression(expression.left, sourceFile, constantScopes);
    const right = resolveRawStringExpression(expression.right, sourceFile, constantScopes);
    return left && right ? routeFromString(left + right) : [];
  }

  return [];
}

function resolveRawStringExpression(
  expression: ts.Expression,
  sourceFile: ts.SourceFile,
  constantScopes: RouteConstantScope[]
): string | null {
  if (ts.isStringLiteralLike(expression)) return expression.text;
  if (ts.isTemplateExpression(expression)) return expression.head.text;
  if (ts.isIdentifier(expression)) {
    const routes = resolveConstantRoutes(expression.text, constantScopes);
    return routes?.length === 1 ? routes[0]! : null;
  }
  if (ts.isParenthesizedExpression(expression)) {
    return resolveRawStringExpression(expression.expression, sourceFile, constantScopes);
  }
  return null;
}

function routeFromTemplateExpression(expression: ts.TemplateExpression) {
  const head = expression.head.text;
  if (!/[?#]/.test(head)) return [];
  return routeFromString(head);
}

function routeFromString(value: string) {
  const route = value.trim().split(/[?#]/, 1)[0];
  if (!route || !route.startsWith("/") || route.startsWith("//")) return [];
  return [route.length > 1 && route.endsWith("/") ? route.slice(0, -1) : route];
}

function isStaticRouteConstantDeclaration(
  node: ts.Node
): node is ts.VariableDeclaration & { name: ts.Identifier; initializer: ts.Expression } {
  return (
    ts.isVariableDeclaration(node) &&
    ts.isIdentifier(node.name) &&
    Boolean(node.initializer) &&
    ts.isVariableDeclarationList(node.parent) &&
    (ts.getCombinedNodeFlags(node.parent) & ts.NodeFlags.Const) !== 0
  );
}

function isApiRequestCall(node: ts.CallExpression) {
  return ts.isIdentifier(node.expression) && node.expression.text === "apiRequest";
}

function isUrlPropertyName(name: ts.PropertyName) {
  return (
    (ts.isIdentifier(name) && name.text === "url") ||
    (ts.isStringLiteralLike(name) && name.text === "url")
  );
}

function addRoute(routes: Map<string, RouteSource[]>, route: string, source: RouteSource) {
  const sources = routes.get(route) ?? [];
  sources.push(source);
  routes.set(route, sources);
}

function createCollectResult(): RouteCollectResult {
  return {
    routes: new Map(),
    unresolvedCalls: []
  };
}

function mergeCollectResult(target: RouteCollectResult, source: RouteCollectResult) {
  for (const [route, sources] of source.routes) {
    for (const routeSource of sources) addRoute(target.routes, route, routeSource);
  }
  target.unresolvedCalls.push(...source.unresolvedCalls);
}

function resolveConstantRoutes(name: string, constantScopes: RouteConstantScope[]) {
  for (let i = constantScopes.length - 1; i >= 0; i--) {
    const routes = constantScopes[i]!.get(name);
    if (routes) return routes;
  }
  return [];
}

function currentScope(constantScopes: RouteConstantScope[]) {
  return constantScopes[constantScopes.length - 1]!;
}

function uniqueRoutes(routes: string[]) {
  return [...new Set(routes)];
}

function getSourceLocation(
  sourceFile: ts.SourceFile,
  filePath: string,
  node: ts.Node
): RouteSource {
  const location = sourceFile.getLineAndCharacterOfPosition(node.getStart(sourceFile));
  return {
    filePath,
    line: location.line + 1,
    column: location.character + 1
  };
}

async function runCli() {
  const args = new Set(process.argv.slice(2));
  if (args.has("--help") || args.has("-h")) {
    console.log(`Usage:
  yarn tsx scripts/generate-ncm-mod-def.ts          Print generated module defs
  yarn tsx scripts/generate-ncm-mod-def.ts --write  Write ${relative(
    REPO_ROOT,
    APP_NCM_MODULE_DEF_FILE
  )}
  yarn tsx scripts/generate-ncm-mod-def.ts --check  Check generated output is up to date`);
    return;
  }

  const content = generateNcmModuleDefContent();

  if (args.has("--check")) {
    const current = readFileSync(APP_NCM_MODULE_DEF_FILE, "utf-8");
    if (current !== content) {
      console.error(`${relative(REPO_ROOT, APP_NCM_MODULE_DEF_FILE)} is not up to date.`);
      process.exitCode = 1;
    }
    return;
  }

  if (args.has("--write")) {
    mkdirSync(dirname(APP_NCM_MODULE_DEF_FILE), { recursive: true });
    writeFileSync(APP_NCM_MODULE_DEF_FILE, content, "utf-8");
    console.log(`Generated ${relative(REPO_ROOT, APP_NCM_MODULE_DEF_FILE)}`);
    return;
  }

  process.stdout.write(content);
}

function isMainModule() {
  return process.argv[1] ? resolve(process.argv[1]) === fileURLToPath(import.meta.url) : false;
}

if (isMainModule()) {
  runCli().catch((error: unknown) => {
    console.error(error instanceof Error ? error.message : error);
    process.exitCode = 1;
  });
}
