// This script is generated by codex
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { test, assert, describe } from "vitest";
import { rmSync, mkdirSync, existsSync, mkdtempSync, writeFileSync } from "node:fs";

import {
  REPO_ROOT,
  formatDiagnostics,
  NCM_API_MODULE_DIR,
  renderNcmModuleDef,
  collectNeteaseApiRoutes,
  routeToModuleIdentifier,
  createNcmModuleDefinitions,
  collectRoutesFromSourceText,
  generateNcmModuleDefContent
} from "./generate-ncm-mod-def";

function withTempDir<T>(run: (dir: string) => T): T {
  const dir = mkdtempSync(join(tmpdir(), "aira-ncm-mod-def-"));
  try {
    return run(dir);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

function writeText(filePath: string, content: string) {
  mkdirSync(resolve(filePath, ".."), { recursive: true });
  writeFileSync(filePath, content, "utf-8");
}

function sortedRoutes(sourceText: string) {
  return [...collectRoutesFromSourceText(sourceText, "sample.ts").routes.keys()].sort();
}

describe("测试网易云模块定义生成脚本", () => {
  describe("路由提取", () => {
    test("能从当前支持的本地写法中提取 apiRequest 路由", () => {
      const result = collectRoutesFromSourceText(
        `
        import { apiRequest } from "@/common/netease/api/request";

        const searchURL = Math.random() > 0.5 ? "/search" : "/cloudsearch";

        apiRequest("/comment/new", { params: {} });
        apiRequest({ url: "/playlist/detail", params: {} });
        apiRequest({ "url": "/playlist/hot" });
        apiRequest({ url: searchURL, params: {} });
        apiRequest(\`/listen/data/report?timestamp=\${Date.now()}\`);
      `,
        "sample.ts"
      );

      assert.deepEqual([...result.routes.keys()].sort(), [
        "/cloudsearch",
        "/comment/new",
        "/listen/data/report",
        "/playlist/detail",
        "/playlist/hot",
        "/search"
      ]);
      assert.deepEqual(result.unresolvedCalls, []);
    });

    test("能解析常量、条件表达式、字符串拼接和类型包装", () => {
      const result = collectRoutesFromSourceText(
        `
        import { apiRequest } from "@/common/netease/api/request";

        const base = "/playlist";
        const detail = (base + "/detail") as string;
        const search = (Math.random() > 0.5 ? "/search" : "/cloudsearch") satisfies string;
        const lyric = "/lyric/new" as const;

        apiRequest({ url: detail });
        apiRequest({ url: search });
        apiRequest({ url: lyric! });
      `,
        "sample.ts"
      );

      assert.deepEqual([...result.routes.keys()].sort(), [
        "/cloudsearch",
        "/lyric/new",
        "/playlist/detail",
        "/search"
      ]);
      assert.deepEqual(result.unresolvedCalls, []);
    });

    test("会规范化 query、hash 和末尾斜杠", () => {
      assert.deepEqual(
        sortedRoutes(`
          import { apiRequest } from "@/common/netease/api/request";

          apiRequest("/playlist/detail?timestamp=1");
          apiRequest("/playlist/hot#top");
          apiRequest("/playlist/create/");
        `),
        ["/playlist/create", "/playlist/detail", "/playlist/hot"]
      );
    });

    test("不会跨无关块级作用域解析常量", () => {
      const result = collectRoutesFromSourceText(
        `
        import { apiRequest } from "@/common/netease/api/request";

        if (enabled) {
          const scopedURL = "/playlist/detail";
        }

        apiRequest({ url: scopedURL });
      `,
        "sample.ts"
      );

      assert.deepEqual([...result.routes.keys()], []);
      assert.equal(result.unresolvedCalls.length, 1);
      assert.equal(result.unresolvedCalls[0]?.message, "Unable to resolve apiRequest route");
    });

    test("内层块级作用域的同名常量会覆盖外层常量", () => {
      const result = collectRoutesFromSourceText(
        `
        import { apiRequest } from "@/common/netease/api/request";

        const route = "/playlist/detail";
        {
          const route = "/search/hot";
          apiRequest({ url: route });
        }
        apiRequest({ url: route });
      `,
        "sample.ts"
      );

      assert.deepEqual([...result.routes.keys()].sort(), ["/playlist/detail", "/search/hot"]);
      assert.deepEqual(result.unresolvedCalls, []);
    });

    test("不会把动态路径模板误解析成半截路由", () => {
      const result = collectRoutesFromSourceText(
        `
        import { apiRequest } from "@/common/netease/api/request";

        apiRequest(\`/playlist/\${id}\`);
      `,
        "sample.ts"
      );

      assert.deepEqual([...result.routes.keys()], []);
      assert.equal(result.unresolvedCalls.length, 1);
    });

    test("只接受本地绝对路径形式的 apiRequest 路由", () => {
      const result = collectRoutesFromSourceText(
        `
        import { apiRequest } from "@/common/netease/api/request";

        apiRequest("https://music.163.com/api/song/lyric");
        apiRequest("//music.163.com/api/song/lyric");
        apiRequest("playlist/detail");
        apiRequest("/playlist/detail");
      `,
        "sample.ts"
      );

      assert.deepEqual([...result.routes.keys()], ["/playlist/detail"]);
      assert.equal(result.unresolvedCalls.length, 3);
    });

    test("不会把非 apiRequest 标识符调用当作网易云接口", () => {
      const result = collectRoutesFromSourceText(
        `
        import { apiRequest as ncmRequest } from "@/common/netease/api/request";

        ncmRequest("/playlist/detail");
        client.apiRequest("/search/hot");
        apiRequestFactory("/song/detail");
      `,
        "sample.ts"
      );

      assert.deepEqual([...result.routes.keys()], []);
      assert.deepEqual(result.unresolvedCalls, []);
    });
  });

  describe("目录扫描", () => {
    test("会递归扫描 ts 文件，并跳过 request.ts 和 d.ts", () => {
      withTempDir((dir) => {
        writeText(
          join(dir, "album.ts"),
          `
          import { apiRequest } from "@/common/netease/api/request";
          apiRequest("/album");
        `
        );
        writeText(
          join(dir, "nested", "playlist.ts"),
          `
          import { apiRequest } from "@/common/netease/api/request";
          apiRequest("/playlist/detail");
        `
        );
        writeText(
          join(dir, "request.ts"),
          `
          import { apiRequest } from "@/common/netease/api/request";
          apiRequest(config);
        `
        );
        writeText(
          join(dir, "types.d.ts"),
          `
          apiRequest("/should/not/scan");
        `
        );

        const result = collectNeteaseApiRoutes(dir);

        assert.deepEqual([...result.routes.keys()].sort(), ["/album", "/playlist/detail"]);
        assert.deepEqual(result.unresolvedCalls, []);
      });
    });
  });

  describe("模块定义生成", () => {
    test("能把上游特殊路由映射到真实模块标识", () => {
      assert.equal(routeToModuleIdentifier("/daily_signin"), "daily_signin");
      assert.equal(routeToModuleIdentifier("/song/url/v1"), "song_url_v1");
    });

    test("会去重、排序，并报告缺失的上游模块文件", () => {
      withTempDir((moduleDir) => {
        writeText(join(moduleDir, "daily_signin.js"), "module.exports = () => null;");
        writeText(join(moduleDir, "song_url_v1.js"), "module.exports = () => null;");

        const definitions = createNcmModuleDefinitions(
          ["/song/url/v1", "/daily_signin", "/song/url/v1", "/missing/module"],
          moduleDir
        );

        assert.deepEqual(
          definitions.entries.map((entry) => [entry.identifier, entry.route]),
          [
            ["daily_signin", "/daily_signin"],
            ["missing_module", "/missing/module"],
            ["song_url_v1", "/song/url/v1"]
          ]
        );
        assert.equal(definitions.missingModuleFiles.length, 1);
        assert.match(
          definitions.missingModuleFiles[0]!.message,
          /Missing upstream NCM module for route \/missing\/module/
        );
      });
    });

    test("能渲染稳定的静态 ModuleDefinition 文件内容", () => {
      const content = renderNcmModuleDef([
        {
          identifier: "playlist_detail",
          route: "/playlist/detail",
          moduleFile: join(NCM_API_MODULE_DIR, "playlist_detail.js")
        },
        {
          identifier: "daily_signin",
          route: "/daily_signin",
          moduleFile: join(NCM_API_MODULE_DIR, "daily_signin.js")
        }
      ]);

      assert.match(content, /auto-generated by scripts\/generate-ncm-mod-def\.ts/);
      assert.match(content, /import \{ createRequire } from "node:module";/);
      assert.match(content, /const moduleDefs: ModuleDefinition\[] = \[/);
      assert.match(content, /route: "\/playlist\/detail"/);
      assert.match(content, /api\/module\/daily_signin"/);
      assert.match(content, /export default moduleDefs;/);
    });

    test("诊断信息会带上相对仓库路径和位置", () => {
      const message = formatDiagnostics([
        {
          filePath: resolve(REPO_ROOT, "scripts/sample.ts"),
          line: 12,
          column: 8,
          message: "Unable to resolve apiRequest route"
        }
      ]);

      assert.equal(
        message,
        `${join("scripts", "sample.ts")}:12:8 Unable to resolve apiRequest route`
      );
    });
  });

  describe("真实项目对账", () => {
    test("当前 UI API 路由都能解析到已安装的 NCM API 模块", () => {
      const collected = collectNeteaseApiRoutes();
      assert.equal(
        collected.unresolvedCalls.length,
        0,
        formatDiagnostics(collected.unresolvedCalls)
      );

      const routes = [...collected.routes.keys()];
      assert.ok(routes.includes("/cloudsearch"));
      assert.ok(routes.includes("/daily_signin"));
      assert.ok(routes.includes("/listen/data/report"));
      assert.ok(routes.includes("/playlist/detail"));

      const definitions = createNcmModuleDefinitions(routes);
      assert.equal(
        definitions.missingModuleFiles.length,
        0,
        formatDiagnostics(definitions.missingModuleFiles)
      );
    });

    test("生成内容覆盖当前 UI API 路由并保留特殊路由", () => {
      const content = generateNcmModuleDefContent();

      assert.match(content, /route: "\/daily_signin"/);
      assert.match(content, /api\/module\/daily_signin"/);
      assert.notMatch(content, /route: "\/daily\/signin"/);
      assert.match(content, /route: "\/playlist\/detail"/);
      assert.match(content, /route: "\/song\/url\/v1"/);
    });

    test("当前生成结果中的每个模块文件都真实存在", () => {
      const definitions = createNcmModuleDefinitions(collectNeteaseApiRoutes().routes.keys());

      for (const entry of definitions.entries) {
        assert.ok(existsSync(entry.moduleFile), `${entry.route} 缺少 ${entry.moduleFile}`);
      }
    });
  });
});
